### ISSUE TITLE
Not support Chinese

### ISSUE THREAD

**Issue by ghost** [codehz/minecraft-unicode-font-texture-generator-online#2]
![snipaste_2018-11-13_20-12-03](https://user-images.githubusercontent.com/26355089/48412711-70da8780-e780-11e8-9169-5fac1f6e86fb.png)

It's force Unicode.
I like the tool, can you please fix it?

**Comment by TomClever** [comment]
我游戏有中文，用过别的字体资源包也有中文，不知道为啥我试着生成好几种字体都是中文不能用

**Comment by TomClever** [comment]
我和原版的对比了一下，发现了一些问题，如图：
![image](https://user-images.githubusercontent.com/26355089/48436448-a2237980-e7b9-11e8-8c20-f9c4c69e6259.png)

**Comment by codehz** [comment]
你这个字体不支持中文的，但是又做了一部分中文字符，所以就有这个问题。。。你试试用手机浏览器跑一个

**Comment by TomClever** [comment]
我试试吧，不知道游戏里面不能显示的原因

**Comment by TomClever** [comment]
我手机不能自动下载生成的文件，能帮我生成一份Arial字体 64x 的资源包吗？邮箱lingjing0921@live.com，谢谢~~~
