### ISSUE TITLE
选PC版的时候生成的目录不对；不支持1.13和1.14；

### ISSUE THREAD

**Issue by Redlnn** [codehz/minecraft-unicode-font-texture-generator-online#4]
- 看了其他 issue 发现老哥会说中文就用中文了。（其实也在知乎上看到了 https://zhuanlan.zhihu.com/p/22779952 ，不过我是在 https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/resource-pack-discussion/2748316-all-version-unicode-hd-font-generator-online-and 那里过来的）
- index.html 第 355-361 行的 switch 少了个 break 导致选PC的时候输出字体文件的路径被下面PE的覆盖掉了。
- 然后是1.13和1.14的字体系统更改了，试了一下那个用 TTF 的方式简直像屎一样，所以还是指望传统的 Unicode ，不过 1.13 和 1.14 的 glyph_sizes.bin 与以前的稍有区别，希望能更进一下 233。我直接用VS打开了1.14的这个bin文件看了一看，发现十六进制状态下每2个字符比如“09”或“0F”对应 Unicode 图片里的一个字，而且是按 Unicode 编码的顺序对应的，所以应该可以解决（我的VS挂了，没法截图不好意思）
- glyph_sizes.bin 的内容的意思貌似与这篇文章相似 https://satgo1546.mist.so/archives/134 ，假如不生成高清字体而是普通的 16x 的话，直接套上 1.14 的 glyph_sizes.bin 是可以用的，不过部分字符的宽度不对，可以用 VS 修改（那这么多字符太麻烦了2333）。
- 另外 C++ 版可以催更吗 233，然后再BBS搜了一下也发现了你的账号，可以试试更新后申精哦

**Comment by codehz** [comment]
你可以push request的——

**Comment by codehz** [comment]
并没有发现1.14和1.12有区别。。。不过看起来多了几个文件
default.json和alt.json

**Comment by codehz** [comment]
目录的问题应该已经修复了

**Comment by Redlnn** [comment]
我看了一下，glyph_sizes.bin的确相同，之前可能我看错了。不过这个网页生成出来的png有alpha通道，Minecraft某些时候会把这个通道去掉然后字体全部糊成一团了,这是否可以通过在网页端改变渲染方式实现呢？这个图是我去掉了部分略透明的像素的效果https://i.loli.net/2019/06/09/5cfcbf837965e29233.jpg

**Comment by codehz** [comment]
这个似乎是不可行的，首先关闭透明通道的后果是文字会出现黑色背景。。（然后在win上还会启用LCD抗锯齿，会出现彩色像素）
其实你那个效果很难用算法描述，直接过滤一定透明度的话，很难控制在刚好一个像素宽度的地方

**Comment by Redlnn** [comment]
好吧，谢谢
